Fix issue7 pytest fixture
EMMC-ASBL/oteapi-plugin-template pull request #8
Opened 2022-01-25 13:45 UTC by pscff

2022-01-25 17:07 UTC, CasperWA requested changes
Cheers @pscff.

I think an import can be removed? If not - this can be approved.

2022-01-25 17:07 UTC, CasperWA commented on {{ cookiecutter.project_slug }}/tests/test_parse.py
>      from oteapi.plugins.plugins import load_plugins
```suggestion
```

I guess this is not needed any more?

2022-01-30 13:49 UTC, CasperWA approved these changes
Cheers @pscff

2022-01-30 13:52 UTC, CasperWA requested changes
Please run `pre-commit run --all-files` and commit and push the changed files.

2022-01-31 08:56 UTC, pscff reviewed
Requested changes done.

2022-01-31 09:01 UTC, CasperWA approved these changes
Look good. I see you've added a `.gitignore` as well. Couldn't hurt 👍

2022-01-31 09:01 UTC, merged